services:
  app:
    image: antoniovna3434/restaurante-antonio:staging
    container_name: restaurante-antonio-container
    ports:
      - "9101:3000"
    environment:
      DB_HOST: mysql-infra
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: password
      DB_NAME: restaurante-antonio-db
    networks:
      - rede_alunos

networks:
  rede_alunos:
    external: true
